name: loja_movil
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 2.0.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  carousel_slider: ^5.0.0
  dynamic_fa_icons: ^1.1.0+2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_native_splash: ^2.3.5
  flutter_session_manager: null
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.5.0
  geolocator: ^12.0.0
  go_router: ^14.2.7
  http: ^1.0.0
  image_picker: ^1.0.1
  intl: ^0.19.0
  latlong2: ^0.9.0
  path: ^1.8.3
  path_provider: ^2.0.15
  provider: ^6.0.5
  share_plus: ^10.0.0
  shared_preferences: ^2.2.2
  sqflite: ^2.2.8+4
  top_snackbar_flutter: ^3.1.0
  url_launcher: ^6.1.14
  vector_math: ^2.1.4
  table_calendar: ^3.0.9
  flutter_map_location_marker: ^9.0.0
  lottie: ^3.0.0
  shimmer: ^3.0.0
  url_strategy: ^0.3.0
  flutter_secure_storage: ^9.2.2
  flutter_hooks: ^0.20.5
  gif_view: ^0.4.4
  http_parser: ^4.0.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^4.19.2

flutter_launcher_icons:
  remove_alpha_ios: true
  image_path:  assets/images/logos/logo_app.png
  android: "launcher_icon"
  ios: true

flutter:
  uses-material-design: true
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir/Avenir-Black.ttf
          weight: 800
        - asset: assets/fonts/avenir/Avenir-Medium.ttf
          weight: 100
    # - family: Poppins
    #   fonts:
    #     - asset: assets/fonts/poppins/Poppins-Thin.ttf
    #     - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
    #       weight: 100
    #     - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
    #     - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
    #       weight: 200
    #     - asset: assets/fonts/poppins/Poppins-Light.ttf
    #     - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
    #       weight: 300
    #     - asset: assets/fonts/poppins/Poppins-Regular.ttf
    #     - asset: assets/fonts/poppins/Poppins-Italic.ttf
    #       weight: 400
    #     - asset: assets/fonts/poppins/Poppins-Medium.ttf
    #     - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
    #       weight: 500
    #     - asset: assets/fonts/poppins/Poppins-Bold.ttf
    #     - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
    #       weight: 700
    #     - asset: assets/fonts/poppins/Poppins-Black.ttf
    #     - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
    #       weight: 900
  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/banner/
    - assets/images/logos/
    - assets/icons/
    - assets/animations/
